import type { Metadata } from "next";
import "./styles/globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import { MainSidebar } from "@/components/nav/MainSidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-slate-50">
        <SidebarProvider name={"Main Sidebar"}>
          <MainSidebar />
          <main>
            <div className="w-full flex overflow-hidden max-h-dvh">
              <div className="w-full h-full">{children}</div>
            </div>
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
