import type { Metadata } from "next";
import "./styles/globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import { MainSidebar } from "@/components/nav/MainSidebar";
import Navbar from "@/components/nav/Navbar";
import Providers from "./_trpc/Providers";
import { Toaster } from "@/components/ui/sonner";
import { SessionProvider } from "next-auth/react";

// TODO: add favicon, fix title and description

export const metadata: Metadata = {
  title: "writerli",
  description: "generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <SessionProvider>
          <body className="bg-slate-50">
            <main>
              <SidebarProvider name={"Main Sidebar"}>
                <MainSidebar />
                <div className="w-full flex flex-col overflow-hidden max-h-dvh">
                  <Navbar />
                  <div className="w-full h-full">{children}</div>
                </div>
              </SidebarProvider>
            </main>
            <Toaster />
          </body>
        </SessionProvider>
      </Providers>
    </html>
  );
}
